### ISSUE TITLE
Missing some files

### ISSUE THREAD

**Issue by hewittzgh** [azizalbastaki/test#1]
@azizalbastaki 
I saw your post on Reddit, and I guess this repository is the repository of your in-game editor.
I wanted to run this project, but some file are missing from the repo, such as water.bam, assets/base/...
Very interesting idea and I find inspiration in you.
I would appreciate it if you could send me the full material files for the modeling.
My email: hewittzgh@gmail.com
Thanks!

**Comment by azizalbastaki** [comment]
Ah, I was wondering why you starred this random repository when I just opened GitHub a minute ago, I just realized that you were looking for the source code of my project, Voyager!

I would like to note that this is actually a really early version of my project, the latest version of my project is at https://github.com/azizalbastaki/Voyager and it should contain all the assets you need to run it, it was set to private, it is public now.

If you have any questions about my project or the Panda3D game engine, please do not hesitate to contact me again.

I would also like to make clear of the commands, WASD to move around, B to turn on the building tool, C to change camera and escape to quit the program

and I also appreciate the praise - thank you! 😄
